"""
Django settings for desphixs project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=_86#m7o1$mi=eq$rjdue=&29f$uxhu5saoj3_a7o@hm$$fm0u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'paypal.standard.ipn',
   #for tag  
    'taggit',
    #for format
    'ckeditor',
    #myapp
    'e_shop',
    'userauths',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'desphixs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'e_shop.context_processor.default',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'desphixs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'userauths/login'

AUTH_USER_MODEL = "userauths.User"

JAZZMIN_SETTINGS = {
    'site_header' : "Desphixs Shop",
    'site_brand' : "You order, we deliver",
    'site_logo' : "assets/imgs/theme/loading.gif",
    'copyright': "desphixs-shop.com"
}

CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        'codeSnippet_theme': 'monokai',
        'toolbar': 'all',
        'extraPlugins': ','.join(
            [
                'codesnippet',
                'widget',
                'dialog'
            ]
        ),
    }
}

#PAYPAL_RECEIVER_EMAIL = 'desphixsbusiness.paypal.com'
#PAYPAL_TEST = True

BKASH_BASE_URL = 'https://checkout.sandbox.bka.sh/v1.2.0-beta/checkout'  # Use production URL for live transactions
BKASH_APP_KEY = 'nAjRxg1lc6eEMdmwkTHyJxyztc'
BKASH_APP_SECRET = 'AabfRBCBxUxYKGNVpenNEBcfptxjVfPIDGGxlHyXbNPLliopt9oK'
BKASH_USERNAME = '01753335815'
BKASH_PASSWORD = 'Dhrubo@123Dhrubo!'
BKASH_MERCHANT_NUMBER = '01753335815'

DATABASES = {  
    'default': {  
        'ENGINE': 'django.db.backends.mysql',  
        'NAME': 'login_page',  
        'USER': 'root',  
        'PASSWORD': '8489659Ma',  
        'HOST': 'localhost',  
        'PORT': '3306', 
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Update with your SMTP server details
EMAIL_PORT = 587  # Update with your SMTP port
EMAIL_USE_TLS = True  # Set it to True if your SMTP server uses TLS
EMAIL_HOST_USER = 'cse12005007brur@gmail.com'  # Update with your email address
EMAIL_HOST_PASSWORD = 'ivps jrir kbnd kmtd'  # Update with your email password
EMAIL_FROM = 'cse12005007brur@gmail.com'
