# Generated by Django 4.2.2 on 2024-09-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
