# Generated by Django 4.2.2 on 2024-09-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0003_adress_cartorder_cartorderitems_category_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('in_review', 'In Review'), ('disabled', 'Disabled'), ('draft', 'Processing'), ('rejected', 'Rejected')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('in_review', 'In Review'), ('disabled', 'Disabled'), ('draft', 'Processing'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[('4', '⭐⭐⭐⭐☆'), ('5', '⭐⭐⭐⭐⭐'), ('3', '⭐⭐⭐☆☆'), ('1', '⭐☆☆☆☆'), ('2', '⭐⭐☆☆☆')], default=None),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
