# Generated by Django 4.2.2 on 2024-09-15 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0007_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('draft', 'Processing'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('published', 'Published')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('draft', 'Processing'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('published', 'Published')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='e_shop.vendor'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[('5', '⭐⭐⭐⭐⭐'), ('1', '⭐☆☆☆☆'), ('4', '⭐⭐⭐⭐☆'), ('3', '⭐⭐⭐☆☆'), ('2', '⭐⭐☆☆☆')], default=None),
        ),
    ]
