# Generated by Django 4.2.2 on 2024-09-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0008_vendor_date_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='cid',
            new_name='vid',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('in_review', 'In Review'), ('draft', 'Processing'), ('rejected', 'Rejected'), ('published', 'Published')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('in_review', 'In Review'), ('draft', 'Processing'), ('rejected', 'Rejected'), ('published', 'Published')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[('3', '⭐⭐⭐☆☆'), ('1', '⭐☆☆☆☆'), ('5', '⭐⭐⭐⭐⭐'), ('2', '⭐⭐☆☆☆'), ('4', '⭐⭐⭐⭐☆')], default=None),
        ),
    ]
