# Generated by Django 4.2.2 on 2024-09-16 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0010_vendor_cover_image_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Processing'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('published', 'Published'), ('disabled', 'Disabled')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Processing'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('published', 'Published'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_images', to='e_shop.product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[('4', '⭐⭐⭐⭐☆'), ('3', '⭐⭐⭐☆☆'), ('2', '⭐⭐☆☆☆'), ('5', '⭐⭐⭐⭐⭐'), ('1', '⭐☆☆☆☆')], default=None),
        ),
    ]
