# Generated by Django 4.2.2 on 2024-09-16 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_shop', '0012_product_life_product_mfd_product_stock_count_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Processing'), ('disabled', 'Disabled'), ('published', 'Published'), ('rejected', 'Rejected'), ('in_review', 'In Review')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Processing'), ('disabled', 'Disabled'), ('published', 'Published'), ('rejected', 'Rejected'), ('in_review', 'In Review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[('3', '⭐⭐⭐☆☆'), ('2', '⭐⭐☆☆☆'), ('5', '⭐⭐⭐⭐⭐'), ('1', '⭐☆☆☆☆'), ('4', '⭐⭐⭐⭐☆')], default=None),
        ),
    ]
