# Generated by Django 4.2.2 on 2024-09-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0014_alter_address_options_product_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('rejected', 'Rejected'), ('draft', 'Processing'), ('in_review', 'In Review'), ('disabled', 'Disabled')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('rejected', 'Rejected'), ('draft', 'Processing'), ('in_review', 'In Review'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[('3', '⭐⭐⭐☆☆'), ('4', '⭐⭐⭐⭐☆'), ('2', '⭐⭐☆☆☆'), ('1', '⭐☆☆☆☆'), ('5', '⭐⭐⭐⭐⭐')], default=None),
        ),
    ]
