# Generated by Django 4.2.2 on 2024-09-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0016_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Processing'), ('disabled', 'Disabled'), ('in_review', 'In Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Processing'), ('disabled', 'Disabled'), ('in_review', 'In Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[('5', '⭐⭐⭐⭐⭐'), ('3', '⭐⭐⭐☆☆'), ('2', '⭐⭐☆☆☆'), ('4', '⭐⭐⭐⭐☆'), ('1', '⭐☆☆☆☆')], default='1'),
        ),
    ]
