# Generated by Django 4.2.2 on 2024-09-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0020_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Processing'), ('in_review', 'In Review'), ('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Processing'), ('in_review', 'In Review'), ('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (4, '⭐⭐⭐⭐☆'), (3, '⭐⭐⭐☆☆'), (1, '⭐☆☆☆☆'), (2, '⭐⭐☆☆☆')], default=None),
        ),
    ]
