# Generated by Django 4.2.2 on 2024-09-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0021_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Processing'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('disabled', 'Disabled')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Processing'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '⭐⭐☆☆☆'), (3, '⭐⭐⭐☆☆'), (1, '⭐☆☆☆☆'), (4, '⭐⭐⭐⭐☆'), (5, '⭐⭐⭐⭐⭐')], default=None),
        ),
    ]
