# Generated by Django 4.2.2 on 2024-09-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0024_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('draft', 'Processing'), ('published', 'Published'), ('rejected', 'Rejected'), ('disabled', 'Disabled')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('draft', 'Processing'), ('published', 'Published'), ('rejected', 'Rejected'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐☆☆☆☆'), (5, '⭐⭐⭐⭐⭐'), (4, '⭐⭐⭐⭐☆'), (2, '⭐⭐☆☆☆'), (3, '⭐⭐⭐☆☆')], default=None),
        ),
    ]
