# Generated by Django 4.2.2 on 2024-09-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0031_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('draft', 'Processing'), ('in_review', 'In Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default='2.99', max_digits=65),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=65),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('draft', 'Processing'), ('in_review', 'In Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐☆☆☆☆'), (4, '⭐⭐⭐⭐☆'), (5, '⭐⭐⭐⭐⭐'), (2, '⭐⭐☆☆☆'), (3, '⭐⭐⭐☆☆')], default=None),
        ),
    ]
